name: flutter_news
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_memory_image: ^1.3.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.0
  intl: ^0.18.0
  photo_manager: ^2.6.0
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
